# Generated by Django 6.0.4 on 2026-04-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('seismic_zone', models.CharField(max_length=10)),
                ('zone_factor', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
            ],
            options={
                'ordering': ['state', 'district'],
                'unique_together': {('state', 'district')},
            },
        ),
    ]
